name: Safe Valkey images

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Valkey 7"
            dockerfile: "./valkey/valkey-7.dockerfile"
            tags: |
              sheplu/safe-image:valkey-7
              sheplu/valkey:7
            platforms: "linux/amd64,linux/arm64"
          - name: "Valkey 7 Alpine"
            dockerfile: "./valkey/valkey-7-alpine.dockerfile"
            tags: |
              sheplu/safe-image:valkey-7-alpine
              sheplu/valkey:7-alpine
            platforms: "linux/amd64,linux/arm64"

          - name: "Valkey 8"
            dockerfile: "./valkey/valkey-8.dockerfile"
            tags: |
              sheplu/safe-image:valkey-8
              sheplu/valkey:8
            platforms: "linux/amd64,linux/arm64"
          - name: "Valkey 8 Alpine"
            dockerfile: "./valkey/valkey-8-alpine.dockerfile"
            tags: |
              sheplu/safe-image:valkey-8-alpine
              sheplu/valkey:8-alpine
            platforms: "linux/amd64,linux/arm64"

          - name: "Valkey 9"
            dockerfile: "./valkey/valkey-9.dockerfile"
            tags: |
              sheplu/safe-image:valkey-9
              sheplu/valkey:9
            platforms: "linux/amd64,linux/arm64"
          - name: "Valkey 9 Alpine"
            dockerfile: "./valkey/valkey-9-alpine.dockerfile"
            tags: |
              sheplu/safe-image:valkey-9-alpine
              sheplu/valkey:9-alpine
            platforms: "linux/amd64,linux/arm64"

          - name: "Valkey Latest"
            dockerfile: "./valkey/valkey-latest.dockerfile"
            tags: |
              sheplu/safe-image:valkey-latest
              sheplu/valkey:latest
            platforms: "linux/amd64,linux/arm64"
          - name: "Valkey Latest Alpine"
            dockerfile: "./valkey/valkey-latest-alpine.dockerfile"
            tags: |
              sheplu/safe-image:valkey-alpine
              sheplu/valkey:alpine
            platforms: "linux/amd64,linux/arm64"
         
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push ${{ matrix.name }} Image
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          tags: ${{ matrix.tags }}
          push: true
          context: .
